name: CI/CD to EC2 - Inventory Services

on:
  push:
    branches: [ "QA" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      # 游댳 Building Microservices in Java (only if applicable)
      - name: Build Java Application
        run: mvn clean package -DskipTests || echo "No Maven project found, skipping..."

      # 游댳 Check files in target folder (for Java)
      - name: List files in target directory
        run: ls -l target/ || echo "No target directory found, skipping..."

      # 游댳 Login en Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # 游댳 Building and Uploading Docker Images for Inventory Microservices
      - name: Build Docker Image
        run: docker build -t anggeloo/microservice-add-inventory:latest .

      - name: Push Docker Image
        run: docker push anggeloo/microservice-add-inventory:latest

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1) Cambiar al directorio donde est치 el docker-compose.yml
            cd /home/ubuntu/

            # 2) Descargar las 칰ltimas im치genes de inventario desde Docker Hub
            docker pull anggeloo/microservice-search-inventory:latest
            docker pull anggeloo/microservice-add-inventory:latest
            docker pull anggeloo/microservice-update-inventory:latest
            docker pull anggeloo/microservice-delete-inventory:latest

            # 3) Detener y eliminar los contenedores previos
            docker-compose down

            # 4) Levantar los nuevos contenedores con las im치genes actualizadas
            docker-compose up -d --remove-orphans

            # 5) Verificar que los contenedores est치n corriendo
            docker ps -a
